import Head from 'next/head'
import React from 'react';
import { useSelector, useDispatch } from "react-redux"
import { Box, Stepper, Step, StepLabel, Button, Divider } from '@mui/material';
import { increment, decrement } from "../features/counterSlice"
import { useGetPokemonByNameQuery } from '../services/query';

const steps = [
  'Select master blaster campaign settings',
  'Create an ad group',
  'Create an ad',
];

const Home = () => {

  const count = useSelector(store => store.counter.value)
  const dispatch = useDispatch()
  console.log("count", count);
  const { data, error, isLoading } = useGetPokemonByNameQuery('bulbasaur')
  console.log("data", data, "error", error, "loading", isLoading);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Stepper activeStep={count} orientation="vertical"
          sx={{ width: 40, border: "1px solid black" }}>
          {steps.map((label) => (
            <Step key={label} style={{ paddingLeft: 5 }}>
              <StepLabel></StepLabel>
            </Step>
          ))}
        </Stepper>
        <Button variant="outlined" title='change step' onClick={() => dispatch(decrement())}>
          Back
        </Button>
        <Divider orientation="vertical" />
        <Button variant="outlined" title='change step' onClick={() => dispatch(increment())}>
          Change step
        </Button>
      </Box>
    </div>
  )
}

export default Home
